/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_echo_brain4j_utils_NativeVector */

#ifndef _Included_net_echo_brain4j_utils_NativeVector
#define _Included_net_echo_brain4j_utils_NativeVector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    length
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_echo_brain4j_utils_NativeVector_length
  (JNIEnv *, jobject);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    sum
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_net_echo_brain4j_utils_NativeVector_sum
  (JNIEnv *, jobject);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    normalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_echo_brain4j_utils_NativeVector_normalize
  (JNIEnv *, jobject);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    scale
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_net_echo_brain4j_utils_NativeVector_scale
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    distance
 * Signature: (Lnet/echo/brain4j/utils/NativeVector;)D
 */
JNIEXPORT jdouble JNICALL Java_net_echo_brain4j_utils_NativeVector_distance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_echo_brain4j_utils_NativeVector_free
  (JNIEnv *, jobject);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_echo_brain4j_utils_NativeVector_init
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_echo_brain4j_utils_NativeVector
 * Method:    initWithData
 * Signature: ([D)J
 */
JNIEXPORT jlong JNICALL Java_net_echo_brain4j_utils_NativeVector_initWithData
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
