/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_echo_brain4j_utils_HelloWorldJNI */

#ifndef _Included_net_echo_brain4j_utils_HelloWorldJNI
#define _Included_net_echo_brain4j_utils_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_echo_brain4j_utils_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_echo_brain4j_utils_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
